### Create Category
POST http://localhost:8080/category/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzA0OTEwMzYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2NzA1Nzc0MzYsImlzcyI6Ik11aGFtbWFkc29kaXEifQ.6SWByJ6sMqaiainJPtOtdQIjMKvckYKEEiVddy9R0ZfkmpRUUICcmvFxqUOs97zyAtso-li2ynsRfRA4YyBTsQ

{
  "nameUz": "Dolzarb xabarlar",
  "nameRu": "Важная новость",
  "nameEng": "Important news"
}